apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer
spec:
  selector:
    app: rabbit-consumer
  ports:
    - port: 5672
      targetPort: 5672

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-consumer
spec:
  serviceName: "rabbit-consumer"
  replicas: 0
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: rabbitmq-consumer
          image: michaelchernov/hw-consumer:1.2
          volumeMounts:
            - name: consumer-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: consumer-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi